### ISSUE TITLE
Inquiry about code release timeline

### ISSUE THREAD

**Issue by AwayFromKeyboardwarrior** [XYPB/CLEFT#1]
Hello.

I'm very interested in your CLEFT framework and would love to test it using my own dataset. The approach looks promising and innovative, especially the use of parameter-efficient fine-tuning with large language models for medical imaging tasks.

I understand that the code is marked as "coming soon" in the README. Would you be able to provide any estimated timeline for when you expect to release the code? Even a rough estimate would be helpful for planning purposes.

Thank you for your work on this project, and I look forward to the full release!

**Comment by XYPB** [comment]
Hi,


Thank you for your interest! So, we are currently working on a challenge with this project and it may take some extra time for me to prepare the code.

However, we promise that we will upload the code within this August, soon after the challenge is over. We will notify you once the code is available!

Once again, thank you for your interest and acknowledgment of our work!


Best,
Yuexi Du

**Comment by XYPB** [comment]
Hi there,

I have just uploaded the source code and the pre-trained model here. Check out and please let me know if you have any further questions!

Again, thank you for your interest in our work!

Best,
Yuexi
